# Generated by Django 3.0.7 on 2020-06-20 09:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('parent_Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
        )
    ]
